### ISSUE TITLE
Question: Why does maxPosts have a limit of 20?

### ISSUE THREAD

**Issue by ajsingh007** [kyco/jquery.kyco.googleplusfeed2#11]
Any links that further describe this limit and why it exists? What does "cannot excced 20 because of Google API in use" mean?

Thanks in advance for any insight

**Comment by Corhero** [comment]
Hi

Sorry for only getting back to you now. I think that comment is not relevant anymore :D I would have to test if it is still relevant.

For v1 of the feed I was using a third party RSS feed and then retrieved that feed via a Google API and for some reason back then the API did not want to return more than 20 posts... here is the original code I had in v1:
```
// Retrieve RSS feed using a handy Google API and http://plusfeed.frosas.net
url: 'http://ajax.googleapis.com/ajax/services/feed/load?v=1.0&num=' + settings.maxPosts + '&callback=?&q=' + encodeURIComponent('http://plusfeed.frosas.net/' + self.id),
```
In v2 (the current version) I actually get the feed directly from Google via the Google+ API (maybe there is still a limit - I would have to test it).

Hope that clears things up.

**Comment by ajsingh007** [comment]
Oh I see. right on, thanks for the reply. Cool plugin, I'll play with it a little more. Cheers!
