### ISSUE TITLE
How to get feeds with the google plus page url

### ISSUE THREAD

**Issue by prspace** [kyco/jquery.kyco.googleplusfeed2#12]
Hello,
I have scenario that in my database all i have is their google plus page url not the page id.
In that case how can i get google plus feeds.

Thanks.

**Comment by Corhero** [comment]
Hi there

We would have to figure out a way to get the ID from the URL and then pass it into the plugin.

What do the URLs look like?

**Comment by prspace** [comment]
As of the new google plus they don't expose the id directly in the url. Now the url looks like this https://plus.google.com/+Eventerprisecom

**Comment by Corhero** [comment]
I will have to check if there is something I can do my side. I see one can use the `people.get` API. That requires auth though... Will try and figure something out.

**Comment by Corhero** [comment]
Hi

I have updated the plugin. If you download the latest version (2.1.3) you will be able to pass in "+Eventerprisecom" into the plugin and it will work.

**Comment by prspace** [comment]
Thak you very much. It will help me and other devs
