### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by richardhughes260** [kyco/jquery.kyco.googleplusfeed2#13]
LOVE IT! Works great!!!!

Would it be possible to query the feed for a hash tag and display the results?

**Comment by caweidmann** [comment]
Hi

Sorry for only responding so late. I'm not sure if that is possible. As far as I know one can only retrieve feed content based on a Google+ ID. I'll investigate this and give some feedback as soon as I know.

**Comment by caweidmann** [comment]
Hi

This is unfortunately not possible. It's only possible to retrieve the following items from the API:
- People
- Activities
- Comments

For more info you can checkout https://developers.google.com/+/web/api/rest/latest/.
