### ISSUE TITLE
Unable to retrieve feed contents.

### ISSUE THREAD

**Issue by charlotteglaze** [kyco/jquery.kyco.googleplusfeed2#15]
The feed was working perfectly on a site of mine, but now it seems to only load "Unable to retrieve feed contents."

Is there a timeout happening, or something like that?

http://www.madmissions.com

**Comment by caweidmann** [comment]
Hi @charlotteglaze 

Thank you for pointing this out.

It is not a timeout but rather the quota limit that gets reached. I have a certain quota for the Google+ API calls the feed makes. This quota is now regularly being reached on a daily basis (the quota limit refreshes every day). Once the limit is reached all calls to the API will fail until the quota limit get refreshed and hence the "Unable to retrieve feed contents" message.

So basically once you see that message it means it will keep showing that message until the quota limit gets refreshed.

I have asked Google to increase the quota limit for the plugin. I'll give feedback here and close this issue once Google has approved the quota increase.

This is a concern for me as I cannot guarantee 100% uptime of the feed on your website. I am doing everything possible to ensure we can get the feed back to an uptime of 100%.

**Comment by caweidmann** [comment]
Hi @charlotteglaze 

Google has increased the quota for the API and you should no longer see downtime of the plugin.
