### ISSUE TITLE
Not supporting with jQuery-3.2.1

### ISSUE THREAD

**Issue by akhilpy** [kyco/jquery.kyco.googleplusfeed2#16]
I  tried to setup this library with my application, it working fine with jQuery 1.11 as given. But my application using jQuery 3.2.1 and with this jQuery it show only 'loading'  box.

![screenshot from 2018-10-29 12-26-09](https://user-images.githubusercontent.com/17291916/47633932-b179b480-db75-11e8-93c2-d69c3068196c.png)

**Comment by caweidmann** [comment]
Hi

I will take a look and see what I can do.

**Comment by caweidmann** [comment]
I have resolved the issue. Plugin is now compatible with jQuery v3.
