### ISSUE TITLE
Not want the header image and show more link

### ISSUE THREAD

**Issue by macch** [kyco/jquery.kyco.googleplusfeed2#5]
Hello 

First of all thanks for this great plugin... You  have done a fantastic job.

I want to  show feed as a kind of list so I want to show title and link of that post.
Can you tell me that how can I customize it.

Also I don't want that header image and show more button at the bottom.

Thank You!

**Comment by Corhero** [comment]
Hi

The quickest way to do this would be to overwrite the styling. Simply hide the elements with CSS.
E.g. to hide the header image you would have a CSS rule like this <code>.kyco_googleplusfeed .feed_header { display: none; } </code>

**Comment by Corhero** [comment]
For the "Show more" button use `.kyco_googleplusfeed .feed_sow_more { display: none; }`

**Comment by macch** [comment]
Thanks for the reply...
But I have done it already.
I have passed blank string for the HTML element for show more.

**Comment by Corhero** [comment]
Cool
