### ISSUE TITLE
Feature Request: Include post images

### ISSUE THREAD

**Issue by qirien** [kyco/jquery.kyco.googleplusfeed2#6]
It would be great to have an option to include the image from the original post. Thank you!

**Comment by Corhero** [comment]
Hi

Thanks for the suggestion. I will consider implementing something like this (if it is possible).

**Comment by Corhero** [comment]
Hi

Version `2.1.0` pulls in images, albums, articles and videos. You can toggle this functionality with the `loadAttachments: true/false` option.
