### ISSUE TITLE
is jquery plugin for display google plus feed is compatible for https

### ISSUE THREAD

**Issue by abhijeetbansode** [kyco/jquery.kyco.googleplusfeed2#7]
i recently change http to https but when i load website then google plus feed not display in website  it shows loading
i attched file plz check and help me out

Thanks
![untitled-1](https://cloud.githubusercontent.com/assets/14109579/9658510/9156e8fc-5267-11e5-9295-6084076a1ec3.jpg)

**Comment by Corhero** [comment]
Hi

Sorry for replying so late. It should work over https as well. I have not done any testing so cannot confirm whether this is a bug or if there is potentially something on your side which is misbehaving. Will try and get to this as soon as I can.

**Comment by Corhero** [comment]
Hi I have resolved the issue. The plugin now also works on HTTPS.
