### ISSUE TITLE
Feed not loading

### ISSUE THREAD

**Issue by jrbenny35** [kyco/jquery.kyco.googleplusfeed2#8]
Hello, great piece of code here. It seems that the widget will not load. Within the div with the class "feed_header" the " a href " tag is set to "#" which is found in the js file. However, looking at your demo's this is supposed to be the link to the google plus user. I followed the code posted on your demo's as well, but I can't get it to work.

 Maybe some insight?

Thanks!

**Comment by Corhero** [comment]
Hi

Sorry for only getting back to you now. The plugin should work out of the box. Do you have the latest version? I just published the latest release. Maybe that fixes your problem? If not, please post some code and I can try and help you.

**Comment by jrbenny35** [comment]
I'm currently at work but I did a bower install and I remember seeing 2.0.4 so I am currently not on the latest. I'll update it and try again tonight.

Thanks!

**Comment by Corhero** [comment]
Ok cool.

**Comment by jrbenny35** [comment]
Just wanted to update and say that it is working now and the 2.1.1 update is even better! Thanks for the help.

**Comment by Corhero** [comment]
Awesome.
