### ISSUE TITLE
Question about loadattachments

### ISSUE THREAD

**Issue by marcie40** [kyco/jquery.kyco.googleplusfeed2#9]
Does the current code limit to what you can do?

For example this is my code I removed the google id for security purposes but If I change the load attachments to true. It stops working. But if I change the feedposts and postincrements lower to 2 it works. Any clues on how to fix that? And yes I am using the current script from its current version.

<center><div class="mydiv"></div></center>

<script>
  $(document).ready(function() {
    $('.mydiv').kycoGooglePlusFeed2({
      id: 'googleplusid',
      feedPosts: 3,           // Feed posts to show on load
      postsIncrement: 3,      // Number of feed posts to show on "Show more" button click
      maxPosts: 20,            // Max number of posts to pull before "Show more" will go to Google+, cannot excced 20 because of Google API in use
      profileImageSize: 50,  // Max is 250
      fadeSpeed: 0,           // Fade-in animation duration
      loadAttachments: false, // Load images, videos, links and other attachments into feed?
      orderBy: 'date',  // Either 'date' or 'popularity'
      sort: 'asc',            // Either 'asc' or 'desc'
      lang: 'en'              // Default language, can also be set to 'de'
    });
  });
</script>

**Comment by Corhero** [comment]
Hi

Can you please post your code then I can try and debug? Not understanding exactly what the issue is.

**Comment by Corhero** [comment]
You will always need a Google+ ID, if that is your question. The plugin does not work without an ID, since it needs an ID to get the feed.

**Comment by marcie40** [comment]
I posted the code not sure why it was removed or posted but here it is again


If I change the load attachments to true. It stops working. 

But if I change the feedposts and postincrements lower to 2 it works with load attachments

<center><div class="mydiv"></div></center>

<script>
  $(document).ready(function() {
    $('.mydiv').kycoGooglePlusFeed2({
      id: '116711254071733526772',
      feedPosts: 3,           // Feed posts to show on load
      postsIncrement: 3,      // Number of feed posts to show on "Show more" button click
      maxPosts: 20,            // Max number of posts to pull before "Show more" will go to Google+, cannot excced 20 because of Google API in use
      profileImageSize: 50,  // Max is 250
      fadeSpeed: 0,           // Fade-in animation duration
      loadAttachments: false, // Load images, videos, links and other attachments into feed?
      orderBy: 'date',  // Either 'date' or 'popularity'
      sort: 'asc',            // Either 'asc' or 'desc'
      lang: 'en'              // Default language, can also be set to 'de'
    });
  });
</script>

**Comment by marcie40** [comment]
Is there a way I can send it to you via email the code is not posting here.

**Comment by caweidmann** [comment]
Yeah support@kyco.io.

**Comment by Corhero** [comment]
Hi this is a bug. There is missing functionality for objectType `note`. Will try and patch as soon as possible.

**Comment by Corhero** [comment]
Hi. This is now patched. You can download the latest version and that should resolve your issue.
